homeurl: "http://jhat.pw"
markdown: redcarpet
highlighter: pygments
timezone: Asia/Shanghai
encoding: UTF-8

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all

sass:
    style: compressed

exclude: ['bin']

defaults:
-
    scope:
        path: "blog"
    values:
        layout: "blog_post"

permalink: /:year/:month/:day/:title.html
paginate: 5
excerpt_separator: "\n\n\n"
author: "Jhat"
title: "Jhat's Blog"
description: "jhat.pw Jhat"
header_img: "/assets/images/home-bg.jpg"

nav_pages: ['photos', 'about']

accounts:
    email: "cpf624@126.com"
    weibo: "jhat"
    github: "cpf624"
    cnzz: "5898421"
