baseurl: ""
url: "http://jhat.org"
homeurl: "http://jhat.org"
assetsurl: "http://jhat.org"
timezone: Asia/Shanghai
encoding: UTF-8
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge
gems: [jekyll-paginate]
plugins: [jekyll-paginate]

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all

sass:
    style: compressed

exclude: ['bin']

defaults:
-
    scope:
        path: ""
    values:
        layout: "blog_post"

permalink: /blog/:year/:month/:day/:title.html
paginate: 5
paginate_path: "page:num"
excerpt_separator: "\n\n\n"
author: "Jhat"
title: "Jhat's Blog"
description: "jhat.org Jhat"
header_img: "/assets/images/home-bg.jpg"

nav_pages: ['pictures', 'about']

accounts:
    email: "cpf624@126.com"
    weibo: "jhat"
    github: "cpf624"
    cnzz: "5898421"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - graph.graffle
